In [1]:
import pandas as pd
import numpy as np
import copy
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree   import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
# Random forest
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split
# compare standalone models for binary classification
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from matplotlib import pyplot
from sklearn.ensemble import StackingClassifier
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Conv1D, LSTM, Dense, Dropout, TimeDistributed, Flatten
from keras.optimizers import Adam
import keras
# Cross-validation
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [80]:
data_path = "./data"
X = pd.read_csv(f'{data_path}/x_train.csv')
y = pd.read_csv(f'{data_path}/y_train.csv')
x_testing = pd.read_csv(f'{data_path}/x_test.csv')
y_testing = pd.read_csv(f'{data_path}/y_test_baseline.csv')

In [81]:
X = X[X.columns[1:]]
X.columns = ['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area_1', 'Wilderness_Area_2', 'Wilderness_Area_3', 'Wilderness_Area_4', 
'Soil_Type_1', 'Soil_Type_2','Soil_Type_3','Soil_Type_4','Soil_Type_5','Soil_Type_6','Soil_Type_7','Soil_Type_8','Soil_Type_9','Soil_Type_10',
'Soil_Type_11','Soil_Type_12','Soil_Type_13','Soil_Type_14','Soil_Type_15','Soil_Type_16','Soil_Type_17','Soil_Type_18','Soil_Type_19','Soil_Type_20',
'Soil_Type_21','Soil_Type_22','Soil_Type_23','Soil_Type_24','Soil_Type_25','Soil_Type_26','Soil_Type_27','Soil_Type_28','Soil_Type_29','Soil_Type_30',
'Soil_Type_31','Soil_Type_32','Soil_Type_33','Soil_Type_34','Soil_Type_35','Soil_Type_36','Soil_Type_37','Soil_Type_38','Soil_Type_39','Soil_Type_40']

y = y[y.columns[1:]]
y.columns=['Cover_Type']

# for testing the models
x_testing = x_testing[x_testing.columns[1:]]
x_testing.columns = ['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area_1', 'Wilderness_Area_2', 'Wilderness_Area_3', 'Wilderness_Area_4', 
'Soil_Type_1', 'Soil_Type_2','Soil_Type_3','Soil_Type_4','Soil_Type_5','Soil_Type_6','Soil_Type_7','Soil_Type_8','Soil_Type_9','Soil_Type_10',
'Soil_Type_11','Soil_Type_12','Soil_Type_13','Soil_Type_14','Soil_Type_15','Soil_Type_16','Soil_Type_17','Soil_Type_18','Soil_Type_19','Soil_Type_20',
'Soil_Type_21','Soil_Type_22','Soil_Type_23','Soil_Type_24','Soil_Type_25','Soil_Type_26','Soil_Type_27','Soil_Type_28','Soil_Type_29','Soil_Type_30',
'Soil_Type_31','Soil_Type_32','Soil_Type_33','Soil_Type_34','Soil_Type_35','Soil_Type_36','Soil_Type_37','Soil_Type_38','Soil_Type_39','Soil_Type_40']
y_testing = y_testing[y_testing.columns[1:]]
y_testing.columns=['Cover_Type']

In [82]:
print(X.shape)
print(y.shape)

(406708, 54)
(406708, 1)


In [83]:
#X = X.drop(columns=["id"],inplace=True)
#y = y.drop(columns=["id"],inplace=True)

In [84]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 10, stratify=y['Cover_Type'])



In [85]:
# For creating the models
print("x_train: ",x_train.shape)
print("y_train: ",y_train.shape)
print("x_test: ",x_test.shape)
print("y_test: ",y_test.shape)
print("x_testing: ",x_testing.shape)

x_train:  (284695, 54)
y_train:  (284695, 1)
x_test:  (122013, 54)
y_test:  (122013, 1)
x_testing:  (174304, 54)


In [86]:
X_train = copy.deepcopy(x_train)
Y_train = copy.deepcopy(y_train)
X_test = copy.deepcopy(x_test)
Y_test = copy.deepcopy(y_test)
X_testing = copy.deepcopy(x_testing)

In [87]:
# After performing copy with dtype = int64
print("x_train: ",X_train.shape)
print("y_train: ",Y_train.shape)
print("x_test: ",X_test.shape)
print("y_test: ",Y_test.shape)
print("x_testing: ",X_testing.shape)
print("y_testing: ",Y_testing.shape)

x_train:  (284695, 54)
y_train:  (284695, 1)
x_test:  (122013, 54)
y_test:  (122013, 1)
x_testing:  (174304, 54)
y_testing:  (174304, 1)


#### Models

In [88]:
def train_using_knn(X_train, y_train):
    knn_model = KNeighborsClassifier(n_neighbors=2)
    knn_model.fit(X_train, y_train)
    return knn_model

In [89]:
def prediction(X_test, clf_object):
    y_pred = clf_object.predict(X_test)
    print("Predicted values: ")
    print(y_pred)
    return y_pred
def calculate_Acc(y_test, y_pred):
    print("Confusion matrix: \n")
    confusion_matrix(y_test, y_pred)
    print("Accuracy: ", accuracy_score(y_test,y_pred)*100)
    print("Report ", classification_report(y_test, y_pred))

In [90]:
X_train

Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
58757        3122       8      8                               175   
105585       2771      52     14                               210   
52500        3091     232      9                               426   
117580       2819     118     24                               134   
293168       2989      22     15                               853   
...           ...     ...    ...                               ...   
278988       2703     120     15                                30   
382701       3099     155     13                                67   
51607        2984     283     11                               180   
271724       3149      84      7                               150   
277103       2269     320     26                               170   

        Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
58757                                3                             2290   
105585                              92                             1365   
52500                               48                             5839   
117580                              19                             3265   
293168                             191                             2903   
...                                ...                              ...   
278988                               8                             2156   
382701                              14                             4781   
51607                               31                             4081   
271724                             -19                             1168   
277103                             111                              541   

        Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
58757             211             223            150   
105585            226             210            114   
52500             206             248            179   
117580            252             211             73   
293168            210             208            131   
...               ...             ...            ...   
278988            245             226            106   
382701            235             241            133   
51607             188             240            192   
271724            230             228            131   
277103            145             205            196   

        Horizontal_Distance_To_Fire_Points  ...  Soil_Type_31  Soil_Type_32  \
58757                                 2280  ...             0             1   
105585                                2125  ...             0             0   
52500                                 1824  ...             0             0   
117580                                1772  ...             0             0   
293168                                 711  ...             0             1   
...                                    ...  ...           ...           ...   
278988                                6476  ...             0             0   
382701                                1348  ...             0             0   
51607                                 1224  ...             0             0   
271724                                1082  ...             0             0   
277103                                 480  ...             0             0   

        Soil_Type_33  Soil_Type_34  Soil_Type_35  Soil_Type_36  Soil_Type_37  \
58757              0             0             0             0             0   
105585             1             0             0             0             0   
52500              0             0             0             0             0   
117580             0             0             0             0             0   
293168             0             0             0             0             0   
...              ...           ...           ...           ...           ...   
278988             0             0             0             0             0   
3827

In [157]:
KNN_model = train_using_knn(X_train, Y_train)
#clf_gini = train_using_gini(X_train, Y_train)
#clf_entropy = train_using_entropy(X_train, Y_train)

###  1. Models using all features as default:
Without any type of analysis or feature selection.

Random forest

In [160]:
# Using splited dataset
print("X_test: ", X_test.shape)
print("Y_test: ", Y_test.shape)
y_knn_real = prediction(X_test, KNN_model)
print(accuracy_score(Y_test, y_knn_real))


X_test:  (122013, 54)
Y_test:  (122013, 1)
Predicted values: 
[1 7 3 ... 2 2 2]
0.9537918090695254


In [182]:
y_knn_real = prediction(x_testing, KNN_model)
print("Modelo final tiene dimensiones: ",y_knn_real.shape)


Predicted values: 
[5 1 2 ... 7 2 2]
Modelo final tiene dimensiones:  (174304,)


In [196]:
len(y_knn_real)

174304

In [197]:
labels = {'Cover_Type':y_knn_real}
labels = pd.DataFrame('id':range(len(y_knn_real)), 'Cover_type':y_knn_real)
print(labels)

SyntaxError: invalid syntax (<ipython-input-197-796a89163c9e>, line 2)

In [192]:
numpy.savetxt("Sebastian_Cajas.csv", labels)

In [170]:
import numpy
y_knn_real = pd.DataFrame(y_knn_real)
y_knn_real = np.around(y_knn_real)
y_knn_real= y_knn_real.astype(numpy.int64)
print(y_knn_real.shape)
print(y_knn_real.dtypes)

(174304, 1)
0    int64
dtype: object


In [173]:
numpy.savetxt("Sebastian_Cajas.csv", y_knn_real)

### Cross-val K-fold

In [99]:
from sklearn import model_selection
from sklearn.model_selection import KFold,cross_val_score
kfold = model_selection.KFold(n_splits=10, random_state=100)
kfold

KFold(n_splits=10, random_state=100, shuffle=False)

In [101]:
results_kfold = model_selection.cross_val_score(KNN_model, X_test, Y_test, cv=kfold)
print("Accuracy: %.2f%%" % (results_kfold.mean()*100.0))

Accuracy: 92.02%


### Feature selection N1

In [155]:
fields = ['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points', ]
X_change = X_train[fields]
x_test_change= X_test[fields]

print(X_change.shape)
print(Y_train.shape)
print(x_test_change.shape)
print(Y_test.shape)

KNN_model = train_using_knn(X_change, Y_train)
y_knn_real = prediction(x_test_change, KNN_model)
print(accuracy_score(Y_test, y_knn_real))


(284695, 10)
(284695, 1)
(122013, 10)
(122013, 1)
Predicted values: 
[1 7 3 ... 2 2 2]
0.9537754173735585


In [ ]:
print("Modelo final tiene dimensiones: ",y_knn_real.shape)

In [102]:
import xgboost as xgb

In [105]:
data_dmatrix = xgb.DMatrix(data=X_train,label=Y_train)
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 10)

In [117]:
xg_reg.fit(X_train,Y_train)
preds = xg_reg.predict(X_test)
print(preds.shape)
print(preds)

[13:38:26] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.1.0/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.
[13:38:28] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.1.0/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.
(122013,)
[1.3306417 3.0297318 2.1898408 ... 1.3960055 1.4976854 1.6263834]


In [149]:
import numpy
a = pd.DataFrame(preds)
a = np.around(a)
a= a.astype(numpy.int64)
print(a.shape)
print(a.dtypes)
preds = a

(122013, 1)
0    int64
dtype: object


In [151]:
print(Y_test.shape)
print(preds.shape)

(122013, 1)
(122013, 1)


In [152]:
print(accuracy_score(Y_test, a))

0.44698515731930205
