In [17]:
import pandas as pd
import numpy as np
import copy
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree   import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
# Random forest
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split
# compare standalone models for binary classification
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from matplotlib import pyplot
from sklearn.ensemble import StackingClassifier
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Conv1D, LSTM, Dense, Dropout, TimeDistributed, Flatten
from keras.optimizers import Adam
import keras
# Cross-validation
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [18]:
data_path = "./data"
X = pd.read_csv(f'{data_path}/x_train.csv')
y = pd.read_csv(f'{data_path}/y_train.csv')
x_testing = pd.read_csv(f'{data_path}/x_test.csv')
y_testing = pd.read_csv(f'{data_path}/y_test_baseline.csv')

In [19]:
X = X[X.columns[1:]]
X.columns = ['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area_1', 'Wilderness_Area_2', 'Wilderness_Area_3', 'Wilderness_Area_4', 
'Soil_Type_1', 'Soil_Type_2','Soil_Type_3','Soil_Type_4','Soil_Type_5','Soil_Type_6','Soil_Type_7','Soil_Type_8','Soil_Type_9','Soil_Type_10',
'Soil_Type_11','Soil_Type_12','Soil_Type_13','Soil_Type_14','Soil_Type_15','Soil_Type_16','Soil_Type_17','Soil_Type_18','Soil_Type_19','Soil_Type_20',
'Soil_Type_21','Soil_Type_22','Soil_Type_23','Soil_Type_24','Soil_Type_25','Soil_Type_26','Soil_Type_27','Soil_Type_28','Soil_Type_29','Soil_Type_30',
'Soil_Type_31','Soil_Type_32','Soil_Type_33','Soil_Type_34','Soil_Type_35','Soil_Type_36','Soil_Type_37','Soil_Type_38','Soil_Type_39','Soil_Type_40']

y = y[y.columns[1:]]
y.columns=['Cover_Type']

# for testing the models
x_testing = x_testing[x_testing.columns[1:]]
x_testing.columns = ['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area_1', 'Wilderness_Area_2', 'Wilderness_Area_3', 'Wilderness_Area_4', 
'Soil_Type_1', 'Soil_Type_2','Soil_Type_3','Soil_Type_4','Soil_Type_5','Soil_Type_6','Soil_Type_7','Soil_Type_8','Soil_Type_9','Soil_Type_10',
'Soil_Type_11','Soil_Type_12','Soil_Type_13','Soil_Type_14','Soil_Type_15','Soil_Type_16','Soil_Type_17','Soil_Type_18','Soil_Type_19','Soil_Type_20',
'Soil_Type_21','Soil_Type_22','Soil_Type_23','Soil_Type_24','Soil_Type_25','Soil_Type_26','Soil_Type_27','Soil_Type_28','Soil_Type_29','Soil_Type_30',
'Soil_Type_31','Soil_Type_32','Soil_Type_33','Soil_Type_34','Soil_Type_35','Soil_Type_36','Soil_Type_37','Soil_Type_38','Soil_Type_39','Soil_Type_40']
y_testing = y_testing[y_testing.columns[1:]]
y_testing.columns=['Cover_Type']

In [20]:
print(X.shape)
print(y.shape)

(406708, 54)
(406708, 1)


In [21]:
#X = X.drop(columns=["id"],inplace=True)
#y = y.drop(columns=["id"],inplace=True)

In [42]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 10, stratify=y['Cover_Type'])



In [43]:
# For creating the models
print("x_train: ",x_train.shape)
print("y_train: ",y_train.shape)
print("x_test: ",x_test.shape)
print("y_test: ",y_test.shape)
print("x_testing: ",x_testing.shape)

x_train:  (284695, 54)
y_train:  (284695, 1)
x_test:  (122013, 54)
y_test:  (122013, 1)
x_testing:  (174304, 54)


In [44]:
X_train = copy.deepcopy(x_train)
Y_train = copy.deepcopy(y_train)
X_test = copy.deepcopy(x_test)
Y_test = copy.deepcopy(y_test)
X_testing = copy.deepcopy(x_testing)

In [45]:
# After performing copy with dtype = int64
print("x_train: ",X_train.shape)
print("y_train: ",Y_train.shape)
print("x_test: ",X_test.shape)
print("y_test: ",Y_test.shape)
print("x_testing: ",X_testing.shape)

x_train:  (284695, 54)
y_train:  (284695, 1)
x_test:  (122013, 54)
y_test:  (122013, 1)
x_testing:  (174304, 54)


#### Models

In [46]:
def create_model():
        #createmodel
    model = Sequential()
    model.add(Dense(12, input_dim = 54, activation="relu"))
    model.add(Dense(8, activation = 'relu'))
    model.add(Dense(7, activation = 'sigmoid'))
    # Compile the model
    model.compile(loss = "binary_crossentropy", optimizer = "adam", metrics=['accuracy'])
    model.summary()
    return model

In [47]:
def prediction(X_test, clf_object):
    y_pred = clf_object.predict(X_test)
    print("Predicted values: ")
    print(y_pred)
    return y_pred
def calculate_Acc(y_test, y_pred):
    print("Confusion matrix: \n")
    confusion_matrix(y_test, y_pred)
    print("Accuracy: ", accuracy_score(y_test,y_pred)*100)
    print("Report ", classification_report(y_test, y_pred))

In [48]:
# Normalize data
X_train = tf.keras.utils.normalize(X_train)
#Y_train = tf.keras.utils.normalize(Y_train).T
print(X_train.shape)
print(Y_train.values.ravel().shape)
model = create_model()

(284695, 54)
(284695,)
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 12)                660       
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_5 (Dense)              (None, 7)                 63        
Total params: 827
Trainable params: 827
Non-trainable params: 0
_________________________________________________________________


In [51]:
from sklearn.preprocessing import LabelBinarizer
Y_train = LabelBinarizer().fit_transform(Y_train)

print(Y_train.shape)
print(Y_train)
#
# X_train = np.asarray(X_train).astype(np.float32)
Y_train = np.asarray(Y_train).astype(np.float32)


(284695, 7)
[[0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]


In [50]:
model.fit(X_train,Y_train, epochs=3, batch_size=10,  verbose=2)

Epoch 1/3
28470/28470 - 25s - loss: 0.2438 - accuracy: 0.5860
Epoch 2/3
28470/28470 - 33s - loss: 0.2058 - accuracy: 0.6732
Epoch 3/3
28470/28470 - 30s - loss: 0.1981 - accuracy: 0.6837


In [60]:
y_pred = model.predict(X_test)
y_pred.shape

(122013, 7)

In [71]:
def decode(datum):
    return np.argmax(datum)
y_pred_dec = []
for i in range(y_pred.shape[0]):
    label = y_pred[i]
    decoded_labels = decode(label)
    y_pred_dec.append(decoded_labels)

In [72]:
print(accuracy_score(Y_test, y_pred_dec))

0.5085113881307729
